#!/usr/bin/env python

#Script to use the Fisher Scientific PPS4102 Top Pan balance in ROS

import rospy
from fisherbrand_pps4102_balance import BalanceDriverROS
            
if __name__ == "__main__": #Object oriented initialization for ROS
    rospy.init_node("scale_driver", anonymous=True) #initialize rospy node
    balance_ROS = BalanceDriverROS() #Create instance of ROS Wrapper
    balance_ROS.on() #Turn on scale (in case turned off)
    rospy.on_shutdown(balance_ROS.off) #Turn off scale when driver is turned off
    rospy.loginfo("Balance driver started")
    rospy.spin()
