#!/usr/bin/env python

#Script to use the Fisher Scientific PPS4102 Top Pan balance in ROS

import rospy
from kern_pcb_balance import KernROS
            
if __name__ == "__main__": #Object oriented initialization for ROS
    rospy.init_node("kern_driver", anonymous=True) #initialize rospy node
    kern_ROS = KernROS() #Create instance of ROS Wrapper
    rospy.loginfo("Kern driver started")
    rospy.spin()
